# Generated by Django 5.2.10 on 2026-08-04 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('discord_id', models.CharField(blank=True, default='', max_length=32)),
                ('discord_username', models.CharField(blank=True, default='', max_length=255)),
                ('discord_avatar_url', models.URLField(blank=True, default='')),
                ('is_guild_member', models.BooleanField(default=False)),
                ('guild_roles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
