# Generated by Django 5.2.10 on 2026-08-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_password',
            field=models.BooleanField(default=False),
        ),
    ]
